/**
 * diffUtil.ts — Unified diff computation for the kurdbox-agent.
 *
 * Provides `computeDiff(original, proposed)` which returns a unified diff
 * string. No external npm packages are used; diff is computed via a pure
 * TypeScript LCS implementation.
 *
 * Requirements: 5.1, 5.5, 5.6
 */

// ---------------------------------------------------------------------------
// Pass-through detection
// ---------------------------------------------------------------------------

/**
 * Returns true when `content` is already a unified diff patch that should be
 * forwarded as-is rather than re-diffed.
 *
 * A unified diff starts with a `---` or `@@` line as its very first non-empty
 * line.  Both prefixes are checked so that patches generated by `git diff`
 * (which start with `---`) and patches that omit the file header but start
 * directly with a hunk marker (`@@`) are both recognised.
 */
function isUnifiedDiff(content: string): boolean {
    const firstLine = content.trimStart().slice(0, 3);
    return firstLine === '---' || firstLine === '@@ ';
}

// ---------------------------------------------------------------------------
// LCS (Longest Common Subsequence) on line arrays
// ---------------------------------------------------------------------------

/**
 * Compute the LCS length table for two arrays of strings.
 * Returns a 2-D number array `dp` where `dp[i][j]` is the length of the LCS
 * of `a[0..i-1]` and `b[0..j-1]`.
 */
function lcsTable(a: string[], b: string[]): number[][] {
    const m = a.length;
    const n = b.length;

    // Allocate a (m+1) × (n+1) table initialised to 0.
    const dp: number[][] = Array.from({ length: m + 1 }, () =>
        new Array<number>(n + 1).fill(0)
    );

    for (let i = 1; i <= m; i++) {
        for (let j = 1; j <= n; j++) {
            if (a[i - 1] === b[j - 1]) {
                dp[i][j] = dp[i - 1][j - 1] + 1;
            } else {
                dp[i][j] = Math.max(dp[i - 1][j], dp[i][j - 1]);
            }
        }
    }

    return dp;
}

// ---------------------------------------------------------------------------
// Diff operation types
// ---------------------------------------------------------------------------

type DiffOp =
    | { kind: 'equal'; line: string }
    | { kind: 'delete'; line: string }
    | { kind: 'insert'; line: string };

/**
 * Backtrack the LCS table to produce a sequence of diff operations
 * representing how to transform `a` into `b`.
 */
function backtrack(
    dp: number[][],
    a: string[],
    b: string[],
    i: number,
    j: number,
    ops: DiffOp[]
): void {
    // Iterative approach to avoid call-stack overflow on large files.
    while (i > 0 || j > 0) {
        if (i > 0 && j > 0 && a[i - 1] === b[j - 1]) {
            ops.push({ kind: 'equal', line: a[i - 1] });
            i--;
            j--;
        } else if (j > 0 && (i === 0 || dp[i][j - 1] >= dp[i - 1][j])) {
            ops.push({ kind: 'insert', line: b[j - 1] });
            j--;
        } else {
            ops.push({ kind: 'delete', line: a[i - 1] });
            i--;
        }
    }
    // ops is built in reverse order; the caller reverses it.
}

// ---------------------------------------------------------------------------
// Hunk / context formatting
// ---------------------------------------------------------------------------

const CONTEXT_LINES = 3;

interface Hunk {
    origStart: number; // 1-based line number in original
    origCount: number;
    newStart: number;  // 1-based line number in proposed
    newCount: number;
    lines: string[];   // formatted lines (prefix ' ', '-', '+')
}

/**
 * Given an ordered list of diff operations (equal/delete/insert), group the
 * changed regions together with up to CONTEXT_LINES of surrounding context
 * and produce an array of Hunk objects.
 */
function buildHunks(ops: DiffOp[]): Hunk[] {
    const hunks: Hunk[] = [];
    const n = ops.length;

    // First, tag each op with its position in original (origIdx) and proposed
    // (newIdx) so we can compute hunk headers.
    let origIdx = 0; // 0-based, for tracking
    let newIdx = 0;

    interface TaggedOp {
        kind: 'equal' | 'delete' | 'insert';
        line: string;
        origLine: number; // 1-based; 0 if not in original
        newLine: number;  // 1-based; 0 if not in proposed
    }

    const tagged: TaggedOp[] = ops.map((op) => {
        const t: TaggedOp = {
            kind: op.kind,
            line: op.line,
            origLine: 0,
            newLine: 0,
        };
        if (op.kind === 'equal') {
            origIdx++;
            newIdx++;
            t.origLine = origIdx;
            t.newLine = newIdx;
        } else if (op.kind === 'delete') {
            origIdx++;
            t.origLine = origIdx;
        } else {
            newIdx++;
            t.newLine = newIdx;
        }
        return t;
    });

    // Identify indices of changed ops.
    const changedIndices: number[] = [];
    for (let i = 0; i < n; i++) {
        if (tagged[i].kind !== 'equal') {
            changedIndices.push(i);
        }
    }

    if (changedIndices.length === 0) {
        return [];
    }

    // Cluster changed ops into groups that share context windows.
    const groups: Array<{ start: number; end: number }> = [];
    let groupStart = Math.max(0, changedIndices[0] - CONTEXT_LINES);
    let groupEnd = Math.min(n - 1, changedIndices[0] + CONTEXT_LINES);

    for (let ci = 1; ci < changedIndices.length; ci++) {
        const idx = changedIndices[ci];
        const candidateStart = Math.max(0, idx - CONTEXT_LINES);

        if (candidateStart <= groupEnd + 1) {
            // Overlapping or adjacent — extend current group.
            groupEnd = Math.min(n - 1, idx + CONTEXT_LINES);
        } else {
            groups.push({ start: groupStart, end: groupEnd });
            groupStart = candidateStart;
            groupEnd = Math.min(n - 1, idx + CONTEXT_LINES);
        }
    }
    groups.push({ start: groupStart, end: groupEnd });

    // Build a Hunk for each group.
    for (const group of groups) {
        const hunkOps = tagged.slice(group.start, group.end + 1);

        const lines: string[] = [];
        let origStart = 0;
        let origCount = 0;
        let newStart = 0;
        let newCount = 0;

        for (const op of hunkOps) {
            if (op.kind === 'equal') {
                lines.push(' ' + op.line);
                if (origStart === 0) { origStart = op.origLine; }
                if (newStart === 0) { newStart = op.newLine; }
                origCount++;
                newCount++;
            } else if (op.kind === 'delete') {
                lines.push('-' + op.line);
                if (origStart === 0) { origStart = op.origLine; }
                origCount++;
            } else {
                lines.push('+' + op.line);
                if (newStart === 0) { newStart = op.newLine; }
                newCount++;
            }
        }

        // Fallback: if a hunk is pure insertions (no original lines), use
        // the insertion point in the original.
        if (origStart === 0) {
            // Find the last equal op before this group to get position.
            if (group.start > 0) {
                for (let k = group.start - 1; k >= 0; k--) {
                    if (tagged[k].kind === 'equal') {
                        origStart = tagged[k].origLine + 1;
                        break;
                    }
                }
            }
            if (origStart === 0) { origStart = 1; }
        }
        if (newStart === 0) {
            if (group.start > 0) {
                for (let k = group.start - 1; k >= 0; k--) {
                    if (tagged[k].kind === 'equal') {
                        newStart = tagged[k].newLine + 1;
                        break;
                    }
                }
            }
            if (newStart === 0) { newStart = 1; }
        }

        hunks.push({ origStart, origCount, newStart, newCount, lines });
    }

    return hunks;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Compute a unified diff between `original` and `proposed` content strings.
 *
 * Behaviour:
 * - If `proposed` is already a unified diff patch (starts with `---` or `@@`),
 *   it is returned as-is (pass-through).
 * - Otherwise a line-level LCS diff is computed and formatted as a unified
 *   diff with `--- original` / `+++ proposed` headers and `@@ … @@` hunk
 *   markers.
 * - If `original === proposed` the strings are identical; an empty string is
 *   returned (no changes to show).
 *
 * Requirements: 5.1, 5.5, 5.6
 */
export function computeDiff(original: string, proposed: string): string {
    // Pass-through: proposed is already a unified diff patch.
    if (isUnifiedDiff(proposed)) {
        return proposed;
    }

    // Fast path: identical content.
    if (original === proposed) {
        return '';
    }

    // Split into lines, preserving empty trailing lines.
    const origLines = original.split('\n');
    const propLines = proposed.split('\n');

    // Remove a synthetic empty string that appears after a trailing newline.
    // We keep them if the original truly has a trailing blank line.
    // (Standard diff behaviour: trailing newline is represented by the last
    //  element being an empty string after split('\n').)

    // Compute LCS table and backtrack to get diff ops.
    const dp = lcsTable(origLines, propLines);
    const ops: DiffOp[] = [];
    backtrack(dp, origLines, propLines, origLines.length, propLines.length, ops);
    ops.reverse();

    // Build hunks from ops.
    const hunks = buildHunks(ops);

    if (hunks.length === 0) {
        return '';
    }

    // Format output.
    const outputLines: string[] = ['--- original', '+++ proposed'];

    for (const hunk of hunks) {
        const header =
            `@@ -${hunk.origStart},${hunk.origCount}` +
            ` +${hunk.newStart},${hunk.newCount} @@`;
        outputLines.push(header);
        for (const line of hunk.lines) {
            outputLines.push(line);
        }
    }

    return outputLines.join('\n');
}
